#!/bin/bash

# Define color values
BLUE='\033[0;34m'
NC='\033[0m'

# Default argument values
rio_addr='roboRIO-1678-FRC.local'
help_flag=''

# Use getopts to set variables according to args
while getopts 'i:acvh' opt; do
  case "${opt}" in
    i) rio_addr=$OPTARG ;;
    h) help_flag='true' ;;
    *) exit 1 ;;
  esac
done

# Define functions for various actions
user_print() {
  printf "${BLUE}$1${NC}\n"
}

deploy_code() {
  user_print "Deploying FRCUserProgram..."
  sshpass -p '' ssh admin@$rio_addr <<'ENDSSH'
kill -9 $(pidof FRCUserProgram)
ENDSSH
  sleep 1.0 # Wait for the file to be removed before we try to write to it
  sshpass -p '' scp bazel-bin/frc1678/frc1678 admin@$rio_addr:/home/lvuser/FRCUserProgram
  sshpass -p '' scp robotCommand admin@$rio_addr:/home/lvuser/robotCommand
}

start_code() {
  user_print "Starting code..."
  sshpass -p '' ssh admin@$rio_addr <<'ENDSSH'
/usr/local/frc/bin/frcKillRobot.sh -t -r;
ENDSSH
}

show_help() {
  echo "Flags:"
  echo "-i rio_addr     Set roborio address"
  echo "                Default: roborio-1678-frc.local"
  echo "-h              That's me!"
  exit
}

# Run needed commands
if [ $help_flag ]
then
  show_help
  exit
fi

deploy_code
start_code
